/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoX;

/**
 *
 * @author Administrator
 */
public class text extends javax.swing.JFrame {

    /**
     * Creates new form text
     */
    public text() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hetThe = new javax.swing.JLabel();
        chuaChonLoaiThe = new javax.swing.JLabel();
        banmuonthemthe = new javax.swing.JLabel();
        chuanhapthe = new javax.swing.JLabel();
        banmuonlaythe = new javax.swing.JLabel();
        matkhaumoi = new javax.swing.JLabel();
        nhapngay = new javax.swing.JLabel();
        khongkhadung = new javax.swing.JLabel();
        banmuonin = new javax.swing.JLabel();
        the1 = new javax.swing.JLabel();
        matkhaucukdung = new javax.swing.JLabel();
        doimatkhauthanhcong = new javax.swing.JLabel();
        nhaplaimatkhaukdung = new javax.swing.JLabel();
        matkhauquangan = new javax.swing.JLabel();
        matkhaumoitrungmatkhaucu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hetThe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hetThe.setText("Hết thẻ!");

        chuaChonLoaiThe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chuaChonLoaiThe.setText("Chưa Chọn Loại Thẻ!");

        banmuonthemthe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        banmuonthemthe.setText("Bạn muốn thêm thẻ?");

        chuanhapthe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chuanhapthe.setText("Chưa Nhập Thông Tin Thẻ");

        banmuonlaythe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        banmuonlaythe.setText("Bạn muốn lấy thẻ?");

        matkhaumoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        matkhaumoi.setText("Nhập mật khẩu mới !");

        nhapngay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nhapngay.setText("Nhập ngày! <31.12.2018>");

        khongkhadung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        khongkhadung.setText("Không khả dụng !");

        banmuonin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        banmuonin.setText("Bạn muốn in thẻ?");

        the1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        the1.setText("Thẻ");

        matkhaucukdung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        matkhaucukdung.setText("Mật khẩu cũ không đúng !");

        doimatkhauthanhcong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        doimatkhauthanhcong.setText("Đổi mật khẩu thành công!");

        nhaplaimatkhaukdung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nhaplaimatkhaukdung.setText("Nhập lại mật khẩu không đúng!");

        matkhauquangan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        matkhauquangan.setText("Mật khẩu quá ngắn!");

        matkhaumoitrungmatkhaucu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        matkhaumoitrungmatkhaucu.setText("Mật khẩu mới trùng mật khẩu cũ!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matkhauquangan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matkhaumoitrungmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hetThe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chuaChonLoaiThe, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banmuonthemthe, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chuanhapthe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banmuonin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(khongkhadung, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nhapngay, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(the1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(banmuonlaythe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matkhaucukdung, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nhaplaimatkhaukdung, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doimatkhauthanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hetThe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapngay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuaChonLoaiThe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khongkhadung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banmuonthemthe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(the1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuanhapthe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(banmuonin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banmuonlaythe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkhaucukdung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nhaplaimatkhaukdung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doimatkhauthanhcong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matkhauquangan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matkhaumoitrungmatkhaucu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(text.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(text.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(text.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(text.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new text().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel banmuonin;
    protected javax.swing.JLabel banmuonlaythe;
    protected javax.swing.JLabel banmuonthemthe;
    protected javax.swing.JLabel chuaChonLoaiThe;
    protected javax.swing.JLabel chuanhapthe;
    public javax.swing.JLabel doimatkhauthanhcong;
    protected javax.swing.JLabel hetThe;
    protected javax.swing.JLabel khongkhadung;
    public javax.swing.JLabel matkhaucukdung;
    protected javax.swing.JLabel matkhaumoi;
    public javax.swing.JLabel matkhaumoitrungmatkhaucu;
    public javax.swing.JLabel matkhauquangan;
    public javax.swing.JLabel nhaplaimatkhaukdung;
    protected javax.swing.JLabel nhapngay;
    protected javax.swing.JLabel the1;
    // End of variables declaration//GEN-END:variables
}
